version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mongodb+srv://sumitkumartiwari627_db_user:nQJTEmRjJk2ICVpl@cluster0.kditvi6.mongodb.net/
      - PORT=8080
      - BROKERAGE_BPS=40
      - TAX_BPS=35
      - PRICE_JOB_INTERVAL=1h
      - PRICE_RANDOM_FLOOR=1200
      - PRICE_RANDOM_CEIL=3200
    restart: unless-stopped
